- name: Install docker on raspberrypi_local
  hosts: myhosts
  become: true # Execute sudo

  tasks:
  - name: Install docker
    apt: # advanced package tool
      name: docker.io
      state: present # apt install
      update_cache: true  # Update apt cache (= apt-get update) before installing, then install docker.io