- name: Install docker on raspberrypi_local
  hosts: myhosts
  become: true # Execute sudo

  tasks:
    - name: Install docker
      ansible.builtin.apt: # advanced package tool
        name: docker.io
        state: present # apt install
        update_cache: true # Run the equivalent of "apt-get update" before the operation to ensure that docker.io exists
        cache_valid_time: 3600 # Only update when older than 1 hour
